name: cafe-loops-widgets
channels:
  - conda-forge
dependencies:
  - jupyterlab=3
  - sidecar
  - ipycanvas
  - bqplot
  - ipyvolume
  - ipyleaflet
  - ipycytoscape
  - branca
  - ipympl
  - xeus-cling
  - xleaflet
  - voila
  - voila-material
